# Generated by Django 2.2.4 on 2019-08-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bd',
            new_name='Bb',
        ),
    ]
